// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/status-im/market-proxy/currency_ratios (interfaces: IClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/client.go . IClient
//

// Package mock_currency_ratios is a generated GoMock package.
package mock_currency_ratios

import (
	reflect "reflect"

	currency_ratios "github.com/status-im/market-proxy/currency_ratios"
	gomock "go.uber.org/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
	isgomock struct{}
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// FetchReferencePrices mocks base method.
func (m *MockIClient) FetchReferencePrices(referenceCoins, currencies []string) (currency_ratios.SimplePricePayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchReferencePrices", referenceCoins, currencies)
	ret0, _ := ret[0].(currency_ratios.SimplePricePayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchReferencePrices indicates an expected call of FetchReferencePrices.
func (mr *MockIClientMockRecorder) FetchReferencePrices(referenceCoins, currencies any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchReferencePrices", reflect.TypeOf((*MockIClient)(nil).FetchReferencePrices), referenceCoins, currencies)
}

// Healthy mocks base method.
func (m *MockIClient) Healthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Healthy indicates an expected call of Healthy.
func (mr *MockIClientMockRecorder) Healthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockIClient)(nil).Healthy))
}
