services:
  market-fetcher:
    build:
      context: ./market-fetcher
      dockerfile: Dockerfile
    volumes:
      - ./market-fetcher/config.yaml:/app/config.yaml
      - ./secrets/coingecko_api_tokens.json:/app/coingecko_api_tokens.json
    environment:
      GO_ENV: 'production'
      PORT: '8081'
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - 'markets-network'
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8081/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: prod
    volumes:
      - ./secrets/.htpasswd:/etc/nginx/.htpasswd:ro
    command: >
      sh -c "cd /nginx-config && 
             chmod +x generate-dev-conf.sh && 
             ./generate-dev-conf.sh /etc/nginx/nginx.conf && 
             nginx -g 'daemon off;'"
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - 'markets-network'
    healthcheck:
      test: ['CMD-SHELL', 'nc -z 0.0.0.0 8080']
      interval: '30s'
      timeout: '30s'
      retries: 3
      start_period: '10s'
    depends_on:
      market-fetcher:
        condition: service_healthy

  frontend:
    build:
      context: ./test-api
      dockerfile: Dockerfile
    volumes:
      - ./test-api:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    networks:
      - 'markets-network'

networks:
  markets-network:
    driver: bridge

