// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/status-im/market-proxy/coingecko_prices (interfaces: PeriodicUpdaterInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/periodic_updater.go . PeriodicUpdaterInterface
//

// Package mock_coingecko_prices is a generated GoMock package.
package mock_coingecko_prices

import (
	context "context"
	reflect "reflect"

	config "github.com/status-im/market-proxy/config"
	gomock "go.uber.org/mock/gomock"
)

// MockPeriodicUpdaterInterface is a mock of PeriodicUpdaterInterface interface.
type MockPeriodicUpdaterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPeriodicUpdaterInterfaceMockRecorder
}

// MockPeriodicUpdaterInterfaceMockRecorder is the mock recorder for MockPeriodicUpdaterInterface.
type MockPeriodicUpdaterInterfaceMockRecorder struct {
	mock *MockPeriodicUpdaterInterface
}

// NewMockPeriodicUpdaterInterface creates a new mock instance.
func NewMockPeriodicUpdaterInterface(ctrl *gomock.Controller) *MockPeriodicUpdaterInterface {
	mock := &MockPeriodicUpdaterInterface{ctrl: ctrl}
	mock.recorder = &MockPeriodicUpdaterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeriodicUpdaterInterface) EXPECT() *MockPeriodicUpdaterInterfaceMockRecorder {
	return m.recorder
}

// ForceUpdate mocks base method.
func (m *MockPeriodicUpdaterInterface) ForceUpdate(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForceUpdate", arg0)
}

// ForceUpdate indicates an expected call of ForceUpdate.
func (mr *MockPeriodicUpdaterInterfaceMockRecorder) ForceUpdate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceUpdate", reflect.TypeOf((*MockPeriodicUpdaterInterface)(nil).ForceUpdate), arg0)
}

// GetCacheData mocks base method.
func (m *MockPeriodicUpdaterInterface) GetCacheData() map[string][]byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheData")
	ret0, _ := ret[0].(map[string][]byte)
	return ret0
}

// GetCacheData indicates an expected call of GetCacheData.
func (mr *MockPeriodicUpdaterInterfaceMockRecorder) GetCacheData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheData", reflect.TypeOf((*MockPeriodicUpdaterInterface)(nil).GetCacheData))
}

// GetCacheDataForTier mocks base method.
func (m *MockPeriodicUpdaterInterface) GetCacheDataForTier(arg0 string) map[string][]byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheDataForTier", arg0)
	ret0, _ := ret[0].(map[string][]byte)
	return ret0
}

// GetCacheDataForTier indicates an expected call of GetCacheDataForTier.
func (mr *MockPeriodicUpdaterInterfaceMockRecorder) GetCacheDataForTier(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheDataForTier", reflect.TypeOf((*MockPeriodicUpdaterInterface)(nil).GetCacheDataForTier), arg0)
}

// Healthy mocks base method.
func (m *MockPeriodicUpdaterInterface) Healthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Healthy indicates an expected call of Healthy.
func (mr *MockPeriodicUpdaterInterfaceMockRecorder) Healthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockPeriodicUpdaterInterface)(nil).Healthy))
}

// SetExtraIds mocks base method.
func (m *MockPeriodicUpdaterInterface) SetExtraIds(arg0 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetExtraIds", arg0)
}

// SetExtraIds indicates an expected call of SetExtraIds.
func (mr *MockPeriodicUpdaterInterfaceMockRecorder) SetExtraIds(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExtraIds", reflect.TypeOf((*MockPeriodicUpdaterInterface)(nil).SetExtraIds), arg0)
}

// SetOnMissingExtraIdsUpdatedCallback mocks base method.
func (m *MockPeriodicUpdaterInterface) SetOnMissingExtraIdsUpdatedCallback(arg0 func(context.Context, map[string][]byte)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnMissingExtraIdsUpdatedCallback", arg0)
}

// SetOnMissingExtraIdsUpdatedCallback indicates an expected call of SetOnMissingExtraIdsUpdatedCallback.
func (mr *MockPeriodicUpdaterInterfaceMockRecorder) SetOnMissingExtraIdsUpdatedCallback(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnMissingExtraIdsUpdatedCallback", reflect.TypeOf((*MockPeriodicUpdaterInterface)(nil).SetOnMissingExtraIdsUpdatedCallback), arg0)
}

// SetOnTopPricesUpdatedCallback mocks base method.
func (m *MockPeriodicUpdaterInterface) SetOnTopPricesUpdatedCallback(arg0 func(context.Context, config.PriceTier, map[string][]byte)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnTopPricesUpdatedCallback", arg0)
}

// SetOnTopPricesUpdatedCallback indicates an expected call of SetOnTopPricesUpdatedCallback.
func (mr *MockPeriodicUpdaterInterfaceMockRecorder) SetOnTopPricesUpdatedCallback(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnTopPricesUpdatedCallback", reflect.TypeOf((*MockPeriodicUpdaterInterface)(nil).SetOnTopPricesUpdatedCallback), arg0)
}

// SetTopMarketIds mocks base method.
func (m *MockPeriodicUpdaterInterface) SetTopMarketIds(arg0 []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTopMarketIds", arg0)
}

// SetTopMarketIds indicates an expected call of SetTopMarketIds.
func (mr *MockPeriodicUpdaterInterfaceMockRecorder) SetTopMarketIds(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTopMarketIds", reflect.TypeOf((*MockPeriodicUpdaterInterface)(nil).SetTopMarketIds), arg0)
}

// Start mocks base method.
func (m *MockPeriodicUpdaterInterface) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockPeriodicUpdaterInterfaceMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPeriodicUpdaterInterface)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockPeriodicUpdaterInterface) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockPeriodicUpdaterInterfaceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockPeriodicUpdaterInterface)(nil).Stop))
}
