// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/status-im/market-proxy/interfaces (interfaces: IExchangeRatesService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/coingecko_exchange_rates.go . IExchangeRatesService
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"

	interfaces "github.com/status-im/market-proxy/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockIExchangeRatesService is a mock of IExchangeRatesService interface.
type MockIExchangeRatesService struct {
	ctrl     *gomock.Controller
	recorder *MockIExchangeRatesServiceMockRecorder
	isgomock struct{}
}

// MockIExchangeRatesServiceMockRecorder is the mock recorder for MockIExchangeRatesService.
type MockIExchangeRatesServiceMockRecorder struct {
	mock *MockIExchangeRatesService
}

// NewMockIExchangeRatesService creates a new mock instance.
func NewMockIExchangeRatesService(ctrl *gomock.Controller) *MockIExchangeRatesService {
	mock := &MockIExchangeRatesService{ctrl: ctrl}
	mock.recorder = &MockIExchangeRatesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExchangeRatesService) EXPECT() *MockIExchangeRatesServiceMockRecorder {
	return m.recorder
}

// ExchangeRates mocks base method.
func (m *MockIExchangeRatesService) ExchangeRates() (interfaces.ExchangeRatesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeRates")
	ret0, _ := ret[0].(interfaces.ExchangeRatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeRates indicates an expected call of ExchangeRates.
func (mr *MockIExchangeRatesServiceMockRecorder) ExchangeRates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeRates", reflect.TypeOf((*MockIExchangeRatesService)(nil).ExchangeRates))
}

// Healthy mocks base method.
func (m *MockIExchangeRatesService) Healthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Healthy indicates an expected call of Healthy.
func (mr *MockIExchangeRatesServiceMockRecorder) Healthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockIExchangeRatesService)(nil).Healthy))
}
