// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/status-im/market-proxy/interfaces (interfaces: ILeaderboardService)
//
// Generated by this command:
//
//	mockgen -destination=interfaces/mocks/coingecko_leaderboard.go github.com/status-im/market-proxy/interfaces ILeaderboardService
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"

	interfaces "github.com/status-im/market-proxy/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockILeaderboardService is a mock of ILeaderboardService interface.
type MockILeaderboardService struct {
	ctrl     *gomock.Controller
	recorder *MockILeaderboardServiceMockRecorder
	isgomock struct{}
}

// MockILeaderboardServiceMockRecorder is the mock recorder for MockILeaderboardService.
type MockILeaderboardServiceMockRecorder struct {
	mock *MockILeaderboardService
}

// NewMockILeaderboardService creates a new mock instance.
func NewMockILeaderboardService(ctrl *gomock.Controller) *MockILeaderboardService {
	mock := &MockILeaderboardService{ctrl: ctrl}
	mock.recorder = &MockILeaderboardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILeaderboardService) EXPECT() *MockILeaderboardServiceMockRecorder {
	return m.recorder
}

// EstimatesCurrency mocks base method.
func (m *MockILeaderboardService) EstimatesCurrency(currency string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimatesCurrency", currency)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EstimatesCurrency indicates an expected call of EstimatesCurrency.
func (mr *MockILeaderboardServiceMockRecorder) EstimatesCurrency(currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimatesCurrency", reflect.TypeOf((*MockILeaderboardService)(nil).EstimatesCurrency), currency)
}

// GetCacheData mocks base method.
func (m *MockILeaderboardService) GetCacheData(convertCurrency string) *interfaces.LeaderboardResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheData", convertCurrency)
	ret0, _ := ret[0].(*interfaces.LeaderboardResponse)
	return ret0
}

// GetCacheData indicates an expected call of GetCacheData.
func (mr *MockILeaderboardServiceMockRecorder) GetCacheData(convertCurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheData", reflect.TypeOf((*MockILeaderboardService)(nil).GetCacheData), convertCurrency)
}

// GetTopPricesQuotes mocks base method.
func (m *MockILeaderboardService) GetTopPricesQuotes(currency, convertCurrency string) interfaces.LeaderboardQuotes {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopPricesQuotes", currency, convertCurrency)
	ret0, _ := ret[0].(interfaces.LeaderboardQuotes)
	return ret0
}

// GetTopPricesQuotes indicates an expected call of GetTopPricesQuotes.
func (mr *MockILeaderboardServiceMockRecorder) GetTopPricesQuotes(currency, convertCurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopPricesQuotes", reflect.TypeOf((*MockILeaderboardService)(nil).GetTopPricesQuotes), currency, convertCurrency)
}

// Healthy mocks base method.
func (m *MockILeaderboardService) Healthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Healthy indicates an expected call of Healthy.
func (mr *MockILeaderboardServiceMockRecorder) Healthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockILeaderboardService)(nil).Healthy))
}
