// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/status-im/market-proxy/interfaces (interfaces: ICurrencyRatiosProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/currency_ratios.go . ICurrencyRatiosProvider
//

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	reflect "reflect"
	time "time"

	interfaces "github.com/status-im/market-proxy/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockICurrencyRatiosProvider is a mock of ICurrencyRatiosProvider interface.
type MockICurrencyRatiosProvider struct {
	ctrl     *gomock.Controller
	recorder *MockICurrencyRatiosProviderMockRecorder
	isgomock struct{}
}

// MockICurrencyRatiosProviderMockRecorder is the mock recorder for MockICurrencyRatiosProvider.
type MockICurrencyRatiosProviderMockRecorder struct {
	mock *MockICurrencyRatiosProvider
}

// NewMockICurrencyRatiosProvider creates a new mock instance.
func NewMockICurrencyRatiosProvider(ctrl *gomock.Controller) *MockICurrencyRatiosProvider {
	mock := &MockICurrencyRatiosProvider{ctrl: ctrl}
	mock.recorder = &MockICurrencyRatiosProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICurrencyRatiosProvider) EXPECT() *MockICurrencyRatiosProviderMockRecorder {
	return m.recorder
}

// GetSnapshot mocks base method.
func (m *MockICurrencyRatiosProvider) GetSnapshot() *interfaces.CurrencyRatiosSnapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSnapshot")
	ret0, _ := ret[0].(*interfaces.CurrencyRatiosSnapshot)
	return ret0
}

// GetSnapshot indicates an expected call of GetSnapshot.
func (mr *MockICurrencyRatiosProviderMockRecorder) GetSnapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshot", reflect.TypeOf((*MockICurrencyRatiosProvider)(nil).GetSnapshot))
}

// GetSpotRatioAgo mocks base method.
func (m *MockICurrencyRatiosProvider) GetSpotRatioAgo(currency string, ago time.Duration) (float64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotRatioAgo", currency, ago)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSpotRatioAgo indicates an expected call of GetSpotRatioAgo.
func (mr *MockICurrencyRatiosProviderMockRecorder) GetSpotRatioAgo(currency, ago any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotRatioAgo", reflect.TypeOf((*MockICurrencyRatiosProvider)(nil).GetSpotRatioAgo), currency, ago)
}

// IsCurrencySupported mocks base method.
func (m *MockICurrencyRatiosProvider) IsCurrencySupported(currency string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCurrencySupported", currency)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCurrencySupported indicates an expected call of IsCurrencySupported.
func (mr *MockICurrencyRatiosProviderMockRecorder) IsCurrencySupported(currency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCurrencySupported", reflect.TypeOf((*MockICurrencyRatiosProvider)(nil).IsCurrencySupported), currency)
}
