// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/status-im/market-proxy/coingecko_token_list (interfaces: IClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/client.go . IClient
//

// Package mock_coingecko_token_list is a generated GoMock package.
package mock_coingecko_token_list

import (
	reflect "reflect"

	coingecko_token_list "github.com/status-im/market-proxy/coingecko_token_list"
	gomock "go.uber.org/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// FetchTokenList mocks base method.
func (m *MockIClient) FetchTokenList(arg0 string) (*coingecko_token_list.TokenList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTokenList", arg0)
	ret0, _ := ret[0].(*coingecko_token_list.TokenList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTokenList indicates an expected call of FetchTokenList.
func (mr *MockIClientMockRecorder) FetchTokenList(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTokenList", reflect.TypeOf((*MockIClient)(nil).FetchTokenList), arg0)
}

// Healthy mocks base method.
func (m *MockIClient) Healthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Healthy indicates an expected call of Healthy.
func (mr *MockIClientMockRecorder) Healthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockIClient)(nil).Healthy))
}
