// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/status-im/market-proxy/coingecko_markets (interfaces: IAPIClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/api_client.go . IAPIClient
//

// Package mock_coingecko_markets is a generated GoMock package.
package mock_coingecko_markets

import (
	reflect "reflect"

	interfaces "github.com/status-im/market-proxy/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockIAPIClient is a mock of IAPIClient interface.
type MockIAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIAPIClientMockRecorder
}

// MockIAPIClientMockRecorder is the mock recorder for MockIAPIClient.
type MockIAPIClientMockRecorder struct {
	mock *MockIAPIClient
}

// NewMockIAPIClient creates a new mock instance.
func NewMockIAPIClient(ctrl *gomock.Controller) *MockIAPIClient {
	mock := &MockIAPIClient{ctrl: ctrl}
	mock.recorder = &MockIAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAPIClient) EXPECT() *MockIAPIClientMockRecorder {
	return m.recorder
}

// FetchPage mocks base method.
func (m *MockIAPIClient) FetchPage(arg0 interfaces.MarketsParams) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPage", arg0)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPage indicates an expected call of FetchPage.
func (mr *MockIAPIClientMockRecorder) FetchPage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPage", reflect.TypeOf((*MockIAPIClient)(nil).FetchPage), arg0)
}

// Healthy mocks base method.
func (m *MockIAPIClient) Healthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Healthy indicates an expected call of Healthy.
func (mr *MockIAPIClientMockRecorder) Healthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockIAPIClient)(nil).Healthy))
}
