// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/status-im/market-proxy/coingecko_exchange_rates (interfaces: IClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/client.go . IClient
//

// Package mock_coingecko_exchange_rates is a generated GoMock package.
package mock_coingecko_exchange_rates

import (
	reflect "reflect"

	coingecko_exchange_rates "github.com/status-im/market-proxy/coingecko_exchange_rates"
	gomock "go.uber.org/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
	isgomock struct{}
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// FetchExchangeRates mocks base method.
func (m *MockIClient) FetchExchangeRates() (coingecko_exchange_rates.ExchangeRatesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchExchangeRates")
	ret0, _ := ret[0].(coingecko_exchange_rates.ExchangeRatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchExchangeRates indicates an expected call of FetchExchangeRates.
func (mr *MockIClientMockRecorder) FetchExchangeRates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchExchangeRates", reflect.TypeOf((*MockIClient)(nil).FetchExchangeRates))
}

// Healthy mocks base method.
func (m *MockIClient) Healthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Healthy indicates an expected call of Healthy.
func (mr *MockIClientMockRecorder) Healthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockIClient)(nil).Healthy))
}
