name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true
        cache-dependency-path: market-fetcher/go.sum

    - name: Install dependencies
      run: |
        cd market-fetcher
        go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: market-fetcher

  static-check:
    name: Run Static Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true
        cache-dependency-path: market-fetcher/go.sum

    - name: Install dependencies
      run: |
        cd market-fetcher
        go mod download

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: |
        cd market-fetcher
        staticcheck ./...

    - name: Run go vet
      run: |
        cd market-fetcher
        go vet ./... 