name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
        cache-dependency-path: market-fetcher/go.sum

    - name: Install dependencies
      run: |
        cd market-fetcher
        go mod download

    - name: Run tests
      id: tests
      run: |
        cd market-fetcher
        go test -v -race ./... 